name: build

# the placeholder `$default-branch` will be automatically replaced with
# the name of the repository's default branch, e.g. main
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  test:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build and Push Image
        run: ./build_push_image_karsajobs_ui.sh
