name: build

on:
  push:
    branches: [karsajobs-ui]
  pull_request:
    branches: [karsajobs-ui]

jobs:
  test:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Build and Push Image
        run: ./build_push_image_karsajobs_ui.sh
        env:
          PASS_GITHUB: ${{ secrets.GCR_PASSWORD }}
